name = input("Enter an artifact name: ")
country = input("Enter a country of origin: ")
period = input("Enter a historical period: ")
year = input("Enter a year of acquisition: ")
location = input("Enter a museum wing: ")

print("\n\n--------------------------------------------------")
print("      THE NATIONAL MUSEUM OF HISTORY")
print("--------------------------------------------------")
print()
print("Artifact:      " + name)
print("Origin:        " + country)
print("Period:        " + period)
print("Acquired:      " + year)
print()
print("Catalog Number: " + 'ACQ-' + year + '-' + country)
print()
print("--------------------------------------------------")
print("Location: "+ location)
print("--------------------------------------------------\n\n")